### ISSUE TITLE
Can't send funds

### ISSUE THREAD

**Issue by oliverlj** [ryo-currency/ryo-gui-wallet#7] opened 2018-06-08 06:25 UTC
hello,
I can't send funds with Ryo 0.1.1.

I got this error : 
[08:23:08] [ERROR] 2018-Jun-08 08:23:08.280706 [RPC0]ERROR /psychocrypt/ryo-emergency/src/wallet/wallet2.cpp:3266 daemon_send_resp.status != CORE_RPC_STATUS_OK. THROW EXCEPTION: error::tx_rejected

**Comment by mosu-forge** [comment] 2018-06-10 23:54
Hey Oliver,

A couple of quick questions:

1) Was your wallet fully synced?

2) Did you restore your wallet from seed words or did you import your old sumo wallet?

3) Is this problem persisting?

**Comment by oliverlj** [comment] 2018-06-12 21:28
Hi,
I did rescan spend and the amount decrease from 100 to 28. I tried to send a transaction, i got a new one but this one stay in yellow.

My wallet is fully synced at 141411 but it show me top block at 144260 like sumokoin chain

**Comment by oliverlj** [comment] 2018-06-12 21:30
if I delete the .ryo folder, it bvegins from the beginning and show me this : [23:29:20] [INFO] [ryod]>>> 2018-Jun-12 23:29:20.259692 [P2P3][175.141.143.45:19733 OUT]Sync data returned a new top block candidate: 701 -> 144261 [Your node is 143560 blocks (398 days) behind]
but top block of ryo is 141412 now ?
Is this normal ?

**Comment by mosu-forge** [comment] 2018-06-12 21:33
Hey Oliver, 

If you haven't already, upgrade to GUI v0.1.2 and see if the problem is gone.  Top block is 141412 and it is normal for now that you see sumo's top block, it doesn't cause any major issues as ryod will never sync to that height. 

Once you upgrade the GUI wallet, resync the daemon, if the problem persists, restore from seed via the GUI wallet. I do not think you will have any problems if you follow those steps.

**Comment by oliverlj** [comment] 2018-06-12 21:39
Thanks,
I did my new test on the 0.1.2.
I will try, it is just long to synced whole blockchain.

**Comment by oliverlj** [comment] 2018-06-15 23:28
All good, i have synchronized the whole blockchain.

Thanks for your time

**Comment by mosu-forge** [comment] 2018-06-17 17:17
Great, I will close this issue.

**Closed by mosu-forge** 2018-06-17 17:17 UTC
